In [1]:
import pandas as pd

In [11]:
draft_data = pd.read_excel(r"C:\Users\jonat\Downloads\nba-past-drafts.xlsx")
draft_data

                    player  year  draft_pos       drafted
0            Dwight Howard  2004          1   first round
1             Emeka Okafor  2004          2   first round
2               Ben Gordon  2004          3   first round
3         Shaun Livingston  2004          4   first round
4             Devin Harris  2004          5   first round
...                    ...   ...        ...           ...
1185         Jalen Slawson  2023         24  second round
1186           Isaiah Wong  2023         25  second round
1187       Tarik Biberovic  2023         26  second round
1188  Trayce Jackson-Davis  2023         27  second round
1189      Chris Livingston  2023         28  second round

[1190 rows x 4 columns]

In [12]:
adv_ncaa_stats = pd.read_excel(r"C:\Users\jonat\Downloads\ncaa-advanced-stats-complete.xlsx\ncaa-advanced-stats-complete.xlsx")
adv_ncaa_stats

,player,cls,year,TS%,eFG%,totalS%,orb%,drb%,trb%,ast%,...,stl%,blk%,usg%,ppr,pps,ORtg,DRtg,eDiff,FIC,PER
0,Michael Haddix,Fr,2003,0.561,0.521,120.8,7.9,11.1,9.5,4.1,...,1.6,3.6,24.0,-4.1,1.4,119.8,108.4,11.4,310.8,26.3
1,Craig Smith,Fr,2003,0.626,0.606,147.9,12.5,17.8,15.2,9.3,...,1.5,2.8,27.4,-4.5,1.5,121.7,104.9,16.8,422.4,26.0
2,Carmelo Anthony,Fr,2003,0.537,0.498,149.6,9.5,19.5,14.8,11.9,...,2.2,2.3,29.3,-1.9,1.3,116.8,92.5,24.3,554.3,25.0
3,Chris Bosh,Fr,2003,0.633,0.596,175.8,11.6,22.3,16.9,7.9,...,1.7,6.8,22.4,-4.6,1.6,120.7,93.5,27.2,453.0,24.7
4,Kee-Kee Clark,Fr,2003,0.541,0.490,164.1,1.4,4.7,3.0,23.7,...,2.4,0.5,32.5,-3.4,1.2,109.1,121.6,-12.5,321.1,24.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15942,Robbie Beran,Sr,2024,0.553,0.522,155.9,5.0,17.8,11.7,9.0,...,1.5,4.2,14.5,-1.3,1.2,105.5,101.4,4.1,171.4,11.9
15943,Fidelis Okereke,Sr,2024,0.546,0.496,114.8,10.9,15.7,13.2,5.0,...,1.9,4.2,18.8,-8.0,1.5,95.5,101.3,-5.8,107.8,11.8
15944,Miguel Ayesa,Sr,2024,0.555,0.534,174.7,2.6,7.1,4.8,4.1,...,1.3,0.0,20.6,-2.9,1.2,104.1,110.0,-5.9,88.9,11.8
15945,Jaykwon Walton,Sr,2024,0.483,0.450,139.5,4.0,12.9,8.5,11.4,...,2.4,1.4,17.5,-0.8,1.1,101.9,105.2,-3.3,195.8,11.8
15946,Tibet Gorener,Sr,2024,0.516,0.492,146.4,4.3,11.3,7.7,4.5,...,0.8,1.1,19.8,-1.9,1.1,102.2,114.9,-12.7,188.9,11.8

In [13]:
ncaa_stats = pd.read_excel(r"C:\Users\jonat\Downloads\ncaa-stats-complete.xlsx\ncaa-stats-complete.xlsx")
ncaa_stats

,player,cls,year,gp,mpg,ppg,fgm,fga,fg%,3pm,...,fta,ft%,orb,drb,rpg,apg,spg,bpg,tov,pf
0,Kee-Kee Clark,Fr,2003,29,38.2,24.9,8.0,20.1,0.396,3.8,...,6.1,0.853,0.8,2.4,3.3,4.2,1.4,0.2,4.0,1.9
1,Carmelo Anthony,Fr,2003,35,36.4,22.2,7.9,17.5,0.453,1.6,...,6.8,0.706,2.9,6.9,9.7,2.2,1.5,0.9,2.2,2.2
2,Darshan Luckey,Fr,2003,28,37.5,21.6,7.2,18.8,0.383,1.6,...,7.2,0.777,0.8,4.4,5.1,1.6,1.7,0.3,4.1,2.3
3,Craig Smith,Fr,2003,31,31.9,19.9,7.8,12.9,0.603,0.1,...,6.3,0.677,3.2,4.7,7.9,1.3,0.9,0.9,2.4,3.4
4,Ike Diogu,Fr,2003,32,32.2,19.0,6.6,10.8,0.609,0.3,...,7.7,0.735,3.1,4.8,7.8,0.8,0.3,1.0,2.8,2.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15942,Ja'Shonte' Wright-McLeish,Sr,2024,32,28.2,6.3,2.3,6.2,0.365,1.3,...,0.8,0.654,0.5,1.2,1.7,0.9,1.3,0.3,0.9,2.5
15943,Santiago Vescovi,Sr,2024,35,25.4,6.3,1.9,5.3,0.368,1.2,...,1.5,0.796,0.7,2.9,3.7,2.5,1.1,0.0,1.0,2.6
15944,Robert Braswell IV,Sr,2024,27,16.7,6.3,2.3,5.2,0.433,1.2,...,0.9,0.667,0.9,0.9,1.7,0.3,0.3,0.3,0.5,1.0
15945,Akol Mawein,Sr,2024,34,18.5,6.3,2.2,4.3,0.503,0.3,...,2.2,0.773,0.9,2.4,3.3,0.9,0.6,0.5,1.2,2.2
15946,Gediminas Mokseckas,Sr,2024,32,27.9,6.3,2.1,5.8,0.364,1.1,...,1.6,0.627,0.3,2.1,2.4,2.0,0.4,0.2,1.7,1.7

In [20]:
class_order = {'Fr': 1, 'So': 2, 'Jr': 3, 'Sr': 4}

# For each dataframe, add a numeric column for sorting
adv_ncaa_stats['cls_numeric'] = adv_ncaa_stats['cls'].map(class_order)
ncaa_stats['cls_numeric'] = ncaa_stats['cls'].map(class_order)

# Keep only the latest class for each player in both dataframes
adv_stats_latest = adv_ncaa_stats.loc[adv_ncaa_stats.groupby('player')['cls_numeric'].idxmax()]
ncaa_stats_latest = ncaa_stats.loc[ncaa_stats.groupby('player')['cls_numeric'].idxmax()]

# Drop the helper column
final_adv_stats = adv_stats_latest.drop('cls_numeric', axis=1)
final_ncaa_stats = ncaa_stats_latest.drop('cls_numeric', axis=1)

In [21]:
draft_stats = draft_data.merge(adv_ncaa_stats, on=['player'], how='outer').merge(ncaa_stats, on=['player'], how='outer')
draft_stats.columns

Index(['player', 'year_x', 'draft_pos', 'drafted', 'cls_x', 'year_y', 'TS%',
       'eFG%', 'totalS%', 'orb%', 'drb%', 'trb%', 'ast%', 'tov%', 'stl%',
       'blk%', 'usg%', 'ppr', 'pps', 'ORtg', 'DRtg', 'eDiff', 'FIC', 'PER',
       'cls_numeric_x', 'cls_y', 'year', 'gp', 'mpg', 'ppg', 'fgm', 'fga',
       'fg%', '3pm', '3pa', '3p%', 'ftm', 'fta', 'ft%', 'orb', 'drb', 'rpg',
       'apg', 'spg', 'bpg', 'tov', 'pf', 'cls_numeric_y'],
      dtype='object')

In [27]:
# Count all null values
draft_stats.isnull().sum()

player               0
year_x           25341
draft_pos        25341
drafted          25341
cls_x             6003
year_y            6003
TS%               6003
eFG%              6003
totalS%           6003
orb%              6003
drb%              6003
trb%              6003
ast%              6003
tov%              6003
stl%              6003
blk%              6003
usg%              6003
ppr               6003
pps               6003
ORtg              6003
DRtg              6003
eDiff             6003
FIC               6003
PER               6003
cls_numeric_x     6003
cls_y             6143
year              6143
gp                6143
mpg               6143
ppg               6143
fgm               6143
fga               6143
fg%               6143
3pm               6143
3pa               6143
3p%               6143
ftm               6143
fta               6143
ft%               6143
orb               6143
drb               6143
rpg               6143
apg               6143
spg               6143
bpg               6143
tov               6143
pf                6143
cls_numeric_y     6143
dtype: int64

In [29]:
draft_stats['year_x'].value_counts()

year_x
2009.0    161
2008.0    134
2007.0    131
2013.0    130
2021.0    128
2012.0    125
2006.0    125
2011.0    125
2015.0    124
2010.0    121
2014.0    118
2020.0    108
2005.0    104
2019.0    100
2004.0     93
2023.0     90
2017.0     89
2016.0     87
2018.0     82
2022.0     77
Name: count, dtype: int64

In [30]:
filtered_draft_stats = draft_stats.dropna(subset=['draft_pos'])

In [31]:
filtered_draft_stats

,player,year_x,draft_pos,drafted,cls_x,year_y,TS%,eFG%,totalS%,orb%,...,ft%,orb,drb,rpg,apg,spg,bpg,tov,pf,cls_numeric_y
43,"A.J. Griffin, Jr.",2022.0,16.0,first round,Fr,2022.0,0.630,0.613,173.2,3.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,A.J. Hammons,2016.0,16.0,second round,Fr,2013.0,0.531,0.495,117.6,11.6,...,0.709,2.3,5.8,8.2,1.1,0.3,2.5,2.0,2.4,4.0
45,A.J. Hammons,2016.0,16.0,second round,Jr,2015.0,0.569,0.540,120.9,12.2,...,0.709,2.3,5.8,8.2,1.1,0.3,2.5,2.0,2.4,4.0
46,A.J. Hammons,2016.0,16.0,second round,Sr,2016.0,0.623,0.601,184.6,11.6,...,0.709,2.3,5.8,8.2,1.1,0.3,2.5,2.0,2.4,4.0
88,A.J. Price,2009.0,22.0,second round,Jr,2008.0,0.551,0.508,155.2,2.7,...,0.721,0.6,2.9,3.5,4.7,0.7,0.0,2.7,1.3,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27563,Zhaire Smith,2018.0,16.0,first round,Fr,2018.0,0.618,0.588,172.2,9.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27564,Zhelin Wang,2016.0,27.0,second round,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27566,Zhou Qi,2016.0,13.0,second round,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27568,Ziaire Williams,2021.0,10.0,first round,Fr,2021.0,0.473,0.431,146.1,2.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27578,Zion Williamson,2019.0,1.0,first round,Fr,2019.0,0.702,0.708,165.9,12.7,...,0.640,3.5,5.4,8.9,2.1,2.1,1.8,2.4,2.1,1.0

In [32]:
filtered_draft_stats.columns

Index(['player', 'year_x', 'draft_pos', 'drafted', 'cls_x', 'year_y', 'TS%',
       'eFG%', 'totalS%', 'orb%', 'drb%', 'trb%', 'ast%', 'tov%', 'stl%',
       'blk%', 'usg%', 'ppr', 'pps', 'ORtg', 'DRtg', 'eDiff', 'FIC', 'PER',
       'cls_numeric_x', 'cls_y', 'year', 'gp', 'mpg', 'ppg', 'fgm', 'fga',
       'fg%', '3pm', '3pa', '3p%', 'ftm', 'fta', 'ft%', 'orb', 'drb', 'rpg',
       'apg', 'spg', 'bpg', 'tov', 'pf', 'cls_numeric_y'],
      dtype='object')

In [33]:
focused_draft_stats = filtered_draft_stats.drop(['drafted', 'year_x','year_y','cls_numeric_x','cls_numeric_y', 'cls_y'], axis=1)

In [34]:
focused_draft_stats.head()

,player,draft_pos,cls_x,TS%,eFG%,totalS%,orb%,drb%,trb%,ast%,...,fta,ft%,orb,drb,rpg,apg,spg,bpg,tov,pf
43,"A.J. Griffin, Jr.",16.0,Fr,0.630,0.613,173.2,3.9,13.6,9.1,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,A.J. Hammons,16.0,Fr,0.531,0.495,117.6,11.6,17.2,14.4,6.2,...,3.8,0.709,2.3,5.8,8.2,1.1,0.3,2.5,2.0,2.4
45,A.J. Hammons,16.0,Jr,0.569,0.540,120.9,12.2,19.7,16.1,9.1,...,3.8,0.709,2.3,5.8,8.2,1.1,0.3,2.5,2.0,2.4
46,A.J. Hammons,16.0,Sr,0.623,0.601,184.6,11.6,24.9,18.7,10.6,...,3.8,0.709,2.3,5.8,8.2,1.1,0.3,2.5,2.0,2.4
88,A.J. Price,22.0,Jr,0.551,0.508,155.2,2.7,8.3,5.7,36.1,...,3.7,0.721,0.6,2.9,3.5,4.7,0.7,0.0,2.7,1.3

In [35]:
top_ten_draft_stats = focused_draft_stats[focused_draft_stats['draft_pos'] <= 10]

In [36]:
top_ten_draft_stats

,player,draft_pos,cls_x,TS%,eFG%,totalS%,orb%,drb%,trb%,ast%,...,fta,ft%,orb,drb,rpg,apg,spg,bpg,tov,pf
202,Aaron Gordon,4.0,Fr,0.503,0.516,127.3,10.3,19.3,15.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369,Adam Morrison,3.0,Fr,0.588,0.564,153.7,6.8,15.4,11.6,13.4,...,4.3,0.758,1.4,4.1,5.5,2.8,0.6,0.5,1.7,1.9
370,Adam Morrison,3.0,Fr,0.588,0.564,153.7,6.8,15.4,11.6,13.4,...,9.4,0.772,1.4,4.1,5.5,1.8,1.1,0.3,2.3,2.0
371,Adam Morrison,3.0,So,0.570,0.539,156.6,4.3,11.1,7.9,17.4,...,4.3,0.758,1.4,4.1,5.5,2.8,0.6,0.5,1.7,1.9
372,Adam Morrison,3.0,So,0.570,0.539,156.6,4.3,11.1,7.9,17.4,...,9.4,0.772,1.4,4.1,5.5,1.8,1.1,0.3,2.3,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27250,"Xavier Tillman, Sr.",5.0,Jr,0.593,0.572,147.7,9.9,24.0,17.5,18.1,...,3.3,0.732,2.5,4.8,7.3,1.6,0.9,1.7,1.5,2.8
27347,Yue Sun,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27394,Zach Collins,10.0,Fr,0.703,0.676,187.2,12.0,23.3,18.4,4.5,...,3.8,0.743,1.7,4.2,5.9,0.4,0.5,1.8,1.5,2.7
27568,Ziaire Williams,10.0,Fr,0.473,0.431,146.1,2.3,15.7,9.5,16.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27578,Zion Williamson,1.0,Fr,0.702,0.708,165.9,12.7,18.2,15.6,14.6,...,6.2,0.640,3.5,5.4,8.9,2.1,2.1,1.8,2.4,2.1

In [44]:
top_ten_draft_stats.loc[top_ten_draft_stats['player'] == 'Yue Sun']

,player,draft_pos,cls_x,TS%,eFG%,totalS%,orb%,drb%,trb%,ast%,...,fta,ft%,orb,drb,rpg,apg,spg,bpg,tov,pf
27347,Yue Sun,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
ncaa_top_ten_draft_stats = top_ten_draft_stats.dropna(subset=['cls_x'])

In [40]:
ncaa_top_ten_draft_stats['cls_x'].value_counts()

cls_x
Fr    196
So    155
Jr    114
Sr     86
Name: count, dtype: int64

In [41]:
ncaa_top_ten_draft_stats.isna().sum()

player        0
draft_pos     0
cls_x         0
TS%           0
eFG%          0
totalS%       0
orb%          0
drb%          0
trb%          0
ast%          0
tov%          0
stl%          0
blk%          0
usg%          0
ppr           0
pps           0
ORtg          0
DRtg          0
eDiff         0
FIC           0
PER           0
year         86
gp           86
mpg          86
ppg          86
fgm          86
fga          86
fg%          86
3pm          86
3pa          86
3p%          86
ftm          86
fta          86
ft%          86
orb          86
drb          86
rpg          86
apg          86
spg          86
bpg          86
tov          86
pf           86
dtype: int64

In [45]:
ncaa_top_ten_draft_stats

,player,draft_pos,cls_x,TS%,eFG%,totalS%,orb%,drb%,trb%,ast%,...,fta,ft%,orb,drb,rpg,apg,spg,bpg,tov,pf
202,Aaron Gordon,4.0,Fr,0.503,0.516,127.3,10.3,19.3,15.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369,Adam Morrison,3.0,Fr,0.588,0.564,153.7,6.8,15.4,11.6,13.4,...,4.3,0.758,1.4,4.1,5.5,2.8,0.6,0.5,1.7,1.9
370,Adam Morrison,3.0,Fr,0.588,0.564,153.7,6.8,15.4,11.6,13.4,...,9.4,0.772,1.4,4.1,5.5,1.8,1.1,0.3,2.3,2.0
371,Adam Morrison,3.0,So,0.570,0.539,156.6,4.3,11.1,7.9,17.4,...,4.3,0.758,1.4,4.1,5.5,2.8,0.6,0.5,1.7,1.9
372,Adam Morrison,3.0,So,0.570,0.539,156.6,4.3,11.1,7.9,17.4,...,9.4,0.772,1.4,4.1,5.5,1.8,1.1,0.3,2.3,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27249,"Xavier Tillman, Sr.",5.0,So,0.652,0.622,163.4,12.9,20.1,16.9,12.9,...,3.3,0.732,2.5,4.8,7.3,1.6,0.9,1.7,1.5,2.8
27250,"Xavier Tillman, Sr.",5.0,Jr,0.593,0.572,147.7,9.9,24.0,17.5,18.1,...,3.3,0.732,2.5,4.8,7.3,1.6,0.9,1.7,1.5,2.8
27394,Zach Collins,10.0,Fr,0.703,0.676,187.2,12.0,23.3,18.4,4.5,...,3.8,0.743,1.7,4.2,5.9,0.4,0.5,1.8,1.5,2.7
27568,Ziaire Williams,10.0,Fr,0.473,0.431,146.1,2.3,15.7,9.5,16.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27578,Zion Williamson,1.0,Fr,0.702,0.708,165.9,12.7,18.2,15.6,14.6,...,6.2,0.640,3.5,5.4,8.9,2.1,2.1,1.8,2.4,2.1

In [47]:
ncaa_top_ten_draft_stats.loc[ncaa_top_ten_draft_stats['player'] == 'Aaron Gordon']

,player,draft_pos,cls_x,TS%,eFG%,totalS%,orb%,drb%,trb%,ast%,...,fta,ft%,orb,drb,rpg,apg,spg,bpg,tov,pf
202,Aaron Gordon,4.0,Fr,0.503,0.516,127.3,10.3,19.3,15.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
complete_ncaa_top_ten_draft_stats = ncaa_top_ten_draft_stats.dropna()

In [49]:
complete_ncaa_top_ten_draft_stats

,player,draft_pos,cls_x,TS%,eFG%,totalS%,orb%,drb%,trb%,ast%,...,fta,ft%,orb,drb,rpg,apg,spg,bpg,tov,pf
369,Adam Morrison,3.0,Fr,0.588,0.564,153.7,6.8,15.4,11.6,13.4,...,4.3,0.758,1.4,4.1,5.5,2.8,0.6,0.5,1.7,1.9
370,Adam Morrison,3.0,Fr,0.588,0.564,153.7,6.8,15.4,11.6,13.4,...,9.4,0.772,1.4,4.1,5.5,1.8,1.1,0.3,2.3,2.0
371,Adam Morrison,3.0,So,0.570,0.539,156.6,4.3,11.1,7.9,17.4,...,4.3,0.758,1.4,4.1,5.5,2.8,0.6,0.5,1.7,1.9
372,Adam Morrison,3.0,So,0.570,0.539,156.6,4.3,11.1,7.9,17.4,...,9.4,0.772,1.4,4.1,5.5,1.8,1.1,0.3,2.3,2.0
373,Adam Morrison,3.0,Jr,0.605,0.556,169.5,4.8,11.9,8.6,11.6,...,4.3,0.758,1.4,4.1,5.5,2.8,0.6,0.5,1.7,1.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27093,Willie Cauley-Stein,6.0,So,0.580,0.596,107.7,12.5,16.1,14.4,5.7,...,3.0,0.372,2.3,3.9,6.2,0.9,0.8,2.1,1.7,2.4
27249,"Xavier Tillman, Sr.",5.0,So,0.652,0.622,163.4,12.9,20.1,16.9,12.9,...,3.3,0.732,2.5,4.8,7.3,1.6,0.9,1.7,1.5,2.8
27250,"Xavier Tillman, Sr.",5.0,Jr,0.593,0.572,147.7,9.9,24.0,17.5,18.1,...,3.3,0.732,2.5,4.8,7.3,1.6,0.9,1.7,1.5,2.8
27394,Zach Collins,10.0,Fr,0.703,0.676,187.2,12.0,23.3,18.4,4.5,...,3.8,0.743,1.7,4.2,5.9,0.4,0.5,1.8,1.5,2.7
27578,Zion Williamson,1.0,Fr,0.702,0.708,165.9,12.7,18.2,15.6,14.6,...,6.2,0.640,3.5,5.4,8.9,2.1,2.1,1.8,2.4,2.1